[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mymlpackage"
version = "0.1.0"
description = "My custom ML algorithm with a Scikit-learn interface"
readme = "README.md"
authors = [{ name="Your Name", email="your@email.com" }]
license = { text = "MIT" }
dependencies = [
    "numpy",
    "scikit-learn"
]